### ISSUE TITLE
[meta]: customer app - add endpoints

### ISSUE THREAD

**Issue by tayzlor** [Capgemini-AIE/aifi-node#10]
Need support for the following endpoints 

- [x] Create customer [/api/customer/v2/customers]
- [x] Entry codes [/api/customer/v2/entry-codes]
- [x] Orders [/api/customer/v2/orders]
- [x] Contests [/api/customer/v2/contests]
- [x] Sessions [/api/customer/v2/sessions]
- [x] Password reset [/api/customer/v2/password-reset]
- [x] Products [/api/customer/v2/products]
