### ISSUE TITLE
[meta]: Add support for store endpoints 

### ISSUE THREAD

**Issue by tayzlor** [Capgemini-AIE/aifi-node#9]
Need support for store endpoints which are on /api/aifi for the following: 

- [ ] Store checkout [/api/aifi/checkouts]
- [ ] Store customer entered [/api/aifi/customers/entered]
- [ ] Store customer walked out [/api/aifi/customers/walked-out]
- [ ] Store verify entry code [/api/aifi/entry-codes/verify]
- [ ] Update store inventory [/api/aifi/inventory/products/{productId}]
